services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - ./build:/usr/share/nginx/html
    environment:
      - NODE_ENV=dev
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
